---
apiVersion: v1
kind: Service
metadata:
  name: pod-service
spec:
  ports:
  - name: pod-service-http
    nodePort: 31781
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: moop
    service: pod-service
  type: NodePort
